- name: Fetch and serve mail
  homebrew: name={{ item }} state=present
  with_items:
    - isync
    - dovecot
    #- lbdb # Talk to AddressBook
    - msmtp # Send mails
    #- notmuch # Finding all the mails
