- name: Remap capslock to control for all keyboards
  shell: >
    defaults -currentHost write -g 'com.apple.keyboard.modifiermapping.{{ item }}-0' -array '<dict><key>HIDKeyboardModifierMappingDst</key><integer>2</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>'
  with_items: keyboard_ids.stdout_lines
